apiVersion: apps/v1
kind: Deployment
metadata:
  name: apppolybot-deployment
  spec:
  selector:
    matchLabels:
      app: polybot
      tier: backend
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: polybot
        tier: backend
    spec:
      containers:
      - name: polybot
        image: shayabudi8/polybot:poly-bot-77