apiVersion: v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
      tier: backend
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
        tier: backend
    spec:
      containers:
      - name: nginx
        image: shayabudi8/nginx:nginx
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8082
          initialDelaySeconds: 40
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8082
          initialDelaySeconds: 40
          periodSeconds: 20
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"